name: Build OH via Bash scripts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  build:

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install dependencies
        run: |
          sudo bash build/install.sh
          mkdir -p /oh-dev/oh-5.1

      - name: Get Source Code
        run: |
          sudo bash build/pull_code.sh

      - name: Build
        run: |
          sudo bash build/build.sh
